heat_template_version: ocata

description: template for a BASTION server and the network

parameters:
  key:
    type: string
    description: Key Name

resources:

  external_security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      description: "Open the port 22 of the Bastion Server"
      rules:
        - remote_ip_prefix: 0.0.0.0/0
          port_range_min: 22
          port_range_max: 22
          protocol: tcp

  internal_security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      description: "Open all the ports inside the private network"
      name: internal_security_group
      rules:
        - remote_ip_prefix: 192.168.2.0/24
          protocol: tcp
        - remote_ip_prefix: 192.168.2.0/24
          protocol: udp
        - remote_ip_prefix: 192.168.2.0/24
          protocol: icmp
        - remote_ip_prefix: 192.168.2.0/24
          protocol: 4
          direction: ingress
        - remote_ip_prefix: 0.0.0.0/0
          direction: egress


  mynet:
    type: OS::Neutron::Net
    properties:
      name: "mynet"

  mysubnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: mynet }
      cidr: "192.168.10.0/24"
      dns_nameservers: [ "192.44.75.10" ]
      ip_version: 4
      allocation_pools:
        - start: "192.168.10.200"
          end: "192.168.10.254"
      name: "mysubnet"

  gateway_router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info:
        network: external
      name: "gateway_router"

  gateway_router_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: gateway_router}
      subnet_id: { get_resource: mysubnet}
       
  bastion_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: mynet}
      security_groups: [ get_resource: external_security_group]
      fixed_ips:
        - subnet_id: { get_resource: mysubnet}
          ip_address: 192.168.10.11

  floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: external
      port_id: { get_resource: bastion_port }

  bastion:
    type: OS::Nova::Server
    properties:
      name: bastion
      image: Ubuntu_16.04.latest
      flavor: m1.small
      key_name: { get_param: key}
      networks:
        - port: { get_resource: bastion_port }
      user_data: |
        #!/bin/bash
        export IP=`ifconfig ens3 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}'`
        export HOSTNAME=`hostname`
        tee -a /etc/hosts <<EOF
        $IP $HOSTNAME
        EOF
        echo 'Acquire::http::Proxy "http://apt-cacher-01.priv.enst-bretagne.fr:3142";' > /etc/apt/apt.conf.d/01proxy
        localectl set-locale LANG=en_US.UTF-8 LANGUAGE="en_US:en"
        reboot


  
