apiVersion: apps/v1
kind: Deployment
metadata:
  name: photographer-deployment
  labels:
    app: photographer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: photographer
  template:
    metadata:
      labels:
        app: photographer
    spec:
      containers:
      - name: photographer-containers
        image: registry.cloud.rennes.enst-bretagne.fr:5000/photographer_service_07
        ports:
        - containerPort: 8090
