apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-containers
        image: registry.cloud.rennes.enst-bretagne.fr:5000/backend_service_07
        ports:
        - containerPort: 8070
